# tox.ini
[tox]
envlist = py310, py312, lint
isolated_build = true
skip_missing_interpreters = true

[testenv]
description = Run tests with installed package
deps =
    pytest
commands =
    pytest tests

[testenv:lint]
description = Run ruff and black
skip_install = true
deps =
    black
    ruff
commands =
    black --check jaxbo/ tests/
    ruff check jaxbo/ tests/